= RHEL Image Mode
:page-layout: home
:!sectids:

[.text-center.strong]
== Resumen

Microlab de RHEL Image Mode para Summit Connect Madrid 2024

RHEL image mode para Red Hat Enterprise Linux (RHEL) es un nuevo método de despliegue que utiliza una aproximación de contenedores para gestionar el sistema operativo mediante contenedores.

Actualmente se encuentra como Technology Preview, es decir que no está soportado para producción, pero se puede empezar a utilizar para irse familiarizando con image mode y ver no solo como encaja sino también que soluciones ofrece a los clientes sobre las problematicas que sufren hoy en día.

RHEL image mode sigue una metodología GitOps y CI/CD para gestionar desde las aplicaciones desplegadas hasta el propio sistema operativo.

[.tiles.browse]
== Browse modules

[.tile]
.xref:01-introduccion.adoc[Get Started]
* xref:01-introduccion.adoc#minikube[Minikube]

[.tile]
.xref:02-deploy.adoc[Deploying]
* xref:02-deploy.adoc#package[Package the Application]
* xref:02-deploy.adoc#deploy[Deploy the Application]